name: create PR

on:
    push:
        branches: [develop]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
              node-version: [18.x]

        steps:
        - uses: actions/checkout@v4
        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v6
          with:
            commit-message: automated PR - merge into main
            title: Sync up changes
            body: Merge develop branch into main
            branch: main
            base: develop
 
