name: CI

on:
    workflow_dispatch:
        inputs:
            name:
                description: "Person to greet"
                default: "World"
                required: true

jobs:
    greet:
        runs-on: ubuntu-latest
        steps:            
            - name: Send greeting
              run: echo "Hello ${{ github.event.inputs.name }}"
            
            - name: Run a multi-line script
              run: |
                echo Add other actions to build
                echo test and deploy your project
 
